### ISSUE TITLE
ft predict-m6a "panicked at 'called `Option::unwrap()`"

### ISSUE THREAD

**Issue by rsisaac** [fiberseq/fibertools-rs#11]
Hello,

I'm currently running into an issue with running fibertools' predict-m6a on a ccs bam file.

To run predict-m6a, I am using the format "ft predict-m6a <input ccs bam> <output>". The specific command resulting in the error:

RUST_BACKTRACE=1 ft predict-m6a -v -s 00.subreads.ccs.bam 00.m6a.bam

This results in:

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /opt/conda/conda-bld/fibertools-rs_1678818402776/_build_env/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-htslib-0.39.5/src/bam/header.rs:88:27
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:48:5
   3: rust_htslib::bam::header::Header::to_hashmap
   4: fibertools_rs::find_pb_polymerase
   5: ft::main

Running with RUST_BACKTRACE=full gives:

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /opt/conda/conda-bld/fibertools-rs_1678818402776/_build_env/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-htslib-0.39.5/src/bam/header.rs:88:27
stack backtrace:
   0:     0x55832d205240 - std::backtrace_rs::backtrace::libunwind::trace::h32eb3e08e874dd27
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55832d205240 - std::backtrace_rs::backtrace::trace_unsynchronized::haa3f451d27bc11a5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55832d205240 - std::sys_common::backtrace::_print_fmt::h5b94a01bb4289bb5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55832d205240 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb070b7fa7e3175df
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55832d22737e - core::fmt::write::hd5207aebbb9a86e9
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/fmt/mod.rs:1202:17
   5:     0x55832d2026b5 - std::io::Write::write_fmt::h3bd699bbd129ab8a
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/io/mod.rs:1679:15
   6:     0x55832d206a73 - std::sys_common::backtrace::_print::h7a21be552fdf58da
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55832d206a73 - std::sys_common::backtrace::print::ha85c41fe4dd80b13
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55832d206a73 - std::panicking::default_hook::{{closure}}::h04cca40023d0eeca
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:295:22
   9:     0x55832d20675f - std::panicking::default_hook::haa3ca8c310ed5402
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:314:9
  10:     0x55832d20711a - std::panicking::rust_panic_with_hook::h7b190ce1a948faac
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:698:17
  11:     0x55832d206fd1 - std::panicking::begin_panic_handler::{{closure}}::hbafbfdc3e1b97f68
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:586:13
  12:     0x55832d2056ec - std::sys_common::backtrace::__rust_end_short_backtrace::hda93e5fef243b4c0
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55832d206d32 - rust_begin_unwind
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
  14:     0x55832cdd6d73 - core::panicking::panic_fmt::h8d17ca1073d9a733
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
  15:     0x55832cdd6c3d - core::panicking::panic::hf0565452d0d0936c
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:48:5
  16:     0x55832cef9428 - rust_htslib::bam::header::Header::to_hashmap::h73fad2d39d4b87fb
  17:     0x55832ce2e8d2 - fibertools_rs::find_pb_polymerase::h0658887c63284580
  18:     0x55832cde0037 - ft::main::h1cd9db990c6f0207
  19:     0x55832cddb403 - std::sys_common::backtrace::__rust_begin_short_backtrace::h71d1c428d361ec99
  20:     0x55832cddb419 - std::rt::lang_start::{{closure}}::h796e2076bdfc77f5
  21:     0x55832d1fcc9f - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb69be6e0857c6cfb
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:283:13
  22:     0x55832d1fcc9f - std::panicking::try::do_call::h396dfc441ee9c786
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
  23:     0x55832d1fcc9f - std::panicking::try::h6cdda972d28b3a4f
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
  24:     0x55832d1fcc9f - std::panic::catch_unwind::h376039ec264e8ef9
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
  25:     0x55832d1fcc9f - std::rt::lang_start_internal::{{closure}}::hc94720ca3d4cb727
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:148:48
  26:     0x55832d1fcc9f - std::panicking::try::do_call::h2422fb95933fa2d5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
  27:     0x55832d1fcc9f - std::panicking::try::h488286b5ec8333ff
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
  28:     0x55832d1fcc9f - std::panic::catch_unwind::h81636549836d2a25
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
  29:     0x55832d1fcc9f - std::rt::lang_start_internal::h6ba1bb743c1e9df9
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:148:20
  30:     0x55832cde0c68 - main
  31:     0x7f92715e0555 - __libc_start_main
  32:     0x55832cdd7109 - <unknown>

Other information:

- fibertools version is 0.1.3
- fibertools installed using conda
- Running fibertools on a Linux-based high-performance computing cluster
- Input CCS bam was generated using ccs with the --hifi-kinetics flag (e.g. ccs —hifi-kinetics -j 20 <subread input bam> <ccs output bam>)
- Received the same error message with several different input ccs bams from different sequencing runs
- Attaching a bam file that is the header+1 read ("small.bam") 
[small.bam.zip](https://github.com/fiberseq/fibertools-rs/files/11192400/small.bam.zip)

**Comment by mrvollger** [comment]
It appears to me that your header is not formatted correctly:
<img width="748" alt="image" src="https://user-images.githubusercontent.com/6935283/230966596-b040eb47-fc24-4639-a2ed-2d0c29192004.png">
See the part that is `BC:`? That should be followed with a chracter that indicates the type bing stored and then some value. 

If I delete that part of the header then fibertools runs fine:
<img width="735" alt="image" src="https://user-images.githubusercontent.com/6935283/230966840-c0c66ea8-7e8a-450e-afa4-42c65339c10a.png">

Unfortunately there is nothing I can do other than suggest you remove this invalid BC entry, since the bam header parsing is handled by rust-htslib which I just use.
