### ISSUE TITLE
ft center formatting minor issue with -w

### ISSUE THREAD

**Issue by ymao4926** [fiberseq/fibertools-rs#21]
### Thanks for using `fibertools-rs`! To help with bug reports I need all the following items:
 - The exact command 

 ft center -m 200 -d 10000 -w -r -t 40 PS00324.fiberseq.aligned.bam sacCer3.centromere.bed>PS00323_center.csv

 - centering column output separated by ',,'

0       -15341,,-15289,,-15268,,-15265,,-15261,,-15250...
1       -15222,,-15221,,-15218,,-15212,,-15196,,-15191...
2       -15112,,-15111,,-14226,,-14202,,-14157,,-13833...
3       -13634,,-13631,,-13461,,-13431,,-13401,,-13395...
4       -13614,,-13612,,-13610,,-13609,,-13568,,-13495...

- file path 

/gscratch/stergachislab/ymao/yeast_centromere/data/

 - Version of fibertools-rs [e.g. v0.0.6]
 - OS: [Linux]

**Comment by mrvollger** [comment]
Fixed in #ea456be. Fix will be in 0.3.2 when released.
