### ISSUE TITLE
Is single-strand data supported?

### ISSUE THREAD

**Issue by sparktx-nathan-johnson** [fiberseq/fibertools-rs#23]
Thank you for making this tool available. I am trying to use the predict-m6a functionality, and my input has hifi kinetics, but it is single-strand data generated per 

https://ccs.how/faq/kinetics.html#what-about-single-strand-reads

and the bam has the ip and pw tags. I have been able to run predict-m6a on double stranded data that has the corresponding fi, fp, ri, and rp tags for pulsewidth and interpulse duration, but not on the single-stranded data; I get a message that the hifi kinetics are not present. I have been referring to the description of the bam tags here: https://ccs.how/faq/bam-output

Could I ask if this tool requires the double-stranded hifi kinetics values to run, and if you see any path to using it with data that has the single-stranded tags instead?

Thanks again.

**Comment by mrvollger** [comment]
Hi, thanks for the kind words about the tool. 

It only works with double stranded kinetics. However if you can convert your single stranded data back into double stranded (I think there might be a pb tool for this) then you can apply ft and all the m6a calls with "A"s will be one strand and all the calls with "T"s will be the other. 

Hopefully that makes some sense and is possible for you. 

Alternatively you could try renaming the kinetics tags with an api like pysam, and fill the reverse kinetics information with just arrays of zeros, and take your existing kinetics information to populate the forward kinetics. 

Best,
Mitchell
