### ISSUE TITLE
Does m6a prediction require fiber-seq preperation

### ISSUE THREAD

**Issue by ASLeonard** [fiberseq/fibertools-rs#24]
Hey Mitchell,

Could you clarify if fibertools is able to predict m6a from normally prepared HiFi reads (with full kinetic data) or if they require the special fiber-seq preparation before sequencing? I ran `ft` on some normally prepared data and the output bam had all the new m6a tags, but the new [preprint](https://www.biorxiv.org/content/10.1101/2023.09.26.559521v1) seems to suggest only the latter is true. The IGV looked similar to yours [here](https://github.com/igvteam/igv/issues/1359), but I'm not sure if mine are all nonsense.

best,
Alex

**Comment by mrvollger** [comment]
Hi there. Thanks for using the tool. 

If you wish to use it as a chromatin accessibility assay then you do need to use the Fiber-seq protocol before sequencing. However if you want to detect endogenous m6a then what you have is sufficient (eukaryotes to my knowledge don't have endogenous DNA m6a.)

What is your use case? 

Cheers,
Mitchell

**Comment by ASLeonard** [comment]
I had several samples of cattle sequenced on a Revio with the full kinetics (but no special preparation) so was thinking I could potentially get an extra layer of data for free out if it. It doesn't sound like that is the case though.

**Comment by mrvollger** [comment]
Yeah sorry. The m6a calls you got are almost certainly just false positives.
