### ISSUE TITLE
Train Revio HiFi data using train-m6A-calling

### ISSUE THREAD

**Issue by choudharis2** [fiberseq/fibertools-rs#27]
Dear Mitchell,

Thank you for creating such a great tool.
We have a HiFi data with kinetics from the Pacbio Revio and we are trying fibertools-rs to get the m6A calls. We have used the following steps to perform the analysis.
```
•	ft predict-m6a – using hifi data 
•	pbmm2 align – use m6A predicted bam to map to ref
•	ft extract – extract the m6A calls in bed form.
```
The question we have is if we have to train the data using train-m6A-calling, if yes at which step we should do that.

Thank you for the help.

**Comment by mrvollger** [comment]
No need to. There is already a revio model in ft! 

Thanks for using.

**Comment by choudharis2** [comment]
Thank you for the prompt response.
