### ISSUE TITLE
Nanopore support

### ISSUE THREAD

**Issue by oushujun** [fiberseq/fibertools-rs#29]
Hello,

Thank you for developing fiber-seq and fiber-tools! I am new to this field. It seems that you can use the m6A-MTase treated gDNA to prepare Nanopore libraries and sequence with Nanopore, and there are many tools available to accurately call m6A in Nanopore data. My question: can Fibertools be used to process Nanopore-called m6A information by skipping the `ft-predict-m6a` step?

Thanks!
Shujun

**Comment by mrvollger** [comment]
Hi @oushujun,

I think all the tooling should work fine with the Nanopore bams by skipping the predict step as you suggest. I know at least one person using `ft add-nucleosomes` with nanopore.

But let me know if you run into any issues, and I will be happy to address them if you can provide example data.

Cheers,
Mitchell

**Comment by oushujun** [comment]
Thank you for the immediate response! Is this the right place to ask about the fiberseq m6A-MTase chemistry? I would like to obtain the currently most adaptative m6A-MTase and apply it in plants.

Thanks!
Shujun

**Comment by mrvollger** [comment]
For that you should reach out to Andrew Stergachis (my PI) to see if you can get an MTA setup for the Hia5 enzyme. absterga@uw.edu

We are working on a protocol paper that covers both the wet and dry aspects of fiberseq but it's not ready yet... 

Cheers,
Mitchell

**Comment by oushujun** [comment]
Thank you Mitchell!

Shujun
