### ISSUE TITLE
failed to run custom build command for `libz-sys v1.1.12`

### ISSUE THREAD

**Issue by ywang285** [fiberseq/fibertools-rs#30]
Hi Mitchell, I am trying to install Fibertools on our cluster for DNA m6A calling. I have tried gcc (12.1.0 and 10.3.0) and cmake (3.20.3 and 3.24.2), but I always get below message, and I am wondering if you have any ideas on what is the issue and how I should fix it, thank you!

$ cargo install --all-features --git https://github.com/fiberseq/fibertools-rs

Updating git repository `https://github.com/fiberseq/fibertools-rs`
  Installing fibertools-rs v0.3.6 (https://github.com/fiberseq/fibertools-rs#9839e249)
    Updating crates.io index
   Compiling libc v0.2.150
   Compiling proc-macro2 v1.0.69
   Compiling unicode-ident v1.0.12
   Compiling cc v1.0.84
   Compiling pkg-config v0.3.27
   Compiling quote v1.0.33
   Compiling autocfg v1.1.0
   Compiling version_check v0.9.4
   Compiling typenum v1.17.0
   Compiling generic-array v0.14.7
   Compiling cfg-if v1.0.0
   Compiling syn v2.0.39
   Compiling syn v1.0.109
   Compiling bzip2-sys v0.1.11+1.0.8
   Compiling vcpkg v0.2.15
   Compiling zstd-sys v2.0.9+zstd.1.5.5
   Compiling getrandom v0.2.11
   Compiling libm v0.2.8
   Compiling crc32fast v1.3.2
   Compiling num-traits v0.2.17
   Compiling cmake v0.1.50
   Compiling libz-sys v1.1.12
   Compiling crypto-common v0.1.6
   Compiling zstd-safe v5.0.2+zstd.1.5.2
   Compiling memchr v2.6.4
   Compiling subtle v2.5.0
   Compiling block-buffer v0.10.4
   Compiling rand_core v0.6.4
   Compiling serde v1.0.192
   Compiling rustix v0.38.21
   Compiling anyhow v1.0.75
   Compiling digest v0.10.7
error: failed to run custom build command for `libz-sys v1.1.12`

Caused by:
  process didn't exit successfully: `/tmp/cargo-install9cypfX/release/build/libz-sys-a821f5c08250087a/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=LIBZ_SYS_STATIC
  cargo:rerun-if-changed=build.rs
  CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-unknown-linux-gnu = None
  CMAKE_GENERATOR_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  running: "gcc" "--version"
  exit status: 0
  running: "c++" "--version"
  exit status: 0
  running: "gcc" "--version"
  exit status: 0
  CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = None
  CMAKE_PREFIX_PATH_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-unknown-linux-gnu = None
  CMAKE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE = None
  CMAKE = None
  running: cd "/tmp/cargo-install9cypfX/release/build/libz-sys-155c7672ee3f03e5/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/home/users/ywang285/.cargo/registr
y/src/index.crates.io-6f17d22bba15001f/libz-sys-1.1.12/src/zlib-ng" "-DBUILD_SHARED_LIBS=OFF" "-DZLIB_COMPAT=ON" "-DZLIB_ENABLE_TESTS=OFF" "-DWITH_GZFILEOP=ON"
 "-DCMAKE_INSTALL_PREFIX=/tmp/cargo-install9cypfX/release/build/libz-sys-155c7672ee3f03e5/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64
" "-DCMAKE_C_COMPILER=/share/software/user/open/gcc/10.3.0/bin/gcc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/
share/software/user/open/gcc/10.3.0/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/share/software/user/ope
n/gcc/10.3.0/bin/gcc" "-DCMAKE_BUILD_TYPE=RelWithDebInfo"
  -- Using CMake version 3.24.2
  -- ZLIB_HEADER_VERSION: 1.2.13
  -- ZLIBNG_HEADER_VERSION: 2.1.3
  -- The C compiler identification is GNU 10.3.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /share/software/user/open/gcc/10.3.0/bin/gcc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Arch detected: 'x86_64'
  -- Basearch of 'x86_64' has been detected as: 'x86'
  -- Performing Test FNO_LTO_AVAILABLE
  -- Performing Test FNO_LTO_AVAILABLE - Success
  -- Looking for sys/auxv.h
  -- Looking for sys/auxv.h - found
  -- Looking for sys/sdt.h
  -- Looking for sys/sdt.h - not found
  -- Looking for unistd.h
  -- Looking for unistd.h - found
  -- Looking for sys/types.h
  -- Looking for sys/types.h - found
  -- Looking for stdint.h
  -- Looking for stdint.h - found
  -- Looking for stddef.h
  -- Looking for stddef.h - found
  -- Check size of off64_t
  -- Check size of off64_t - done
  -- Looking for fseeko
  -- Looking for fseeko - found
  -- Looking for strerror
  -- Looking for strerror - found
  -- Looking for posix_memalign
  -- Looking for posix_memalign - found
  -- Looking for aligned_alloc
  -- Looking for aligned_alloc - found
  -- Performing Test HAVE_NO_INTERPOSITION
  -- Performing Test HAVE_NO_INTERPOSITION - Success
  -- Performing Test HAVE_ATTRIBUTE_VISIBILITY_HIDDEN
  -- Performing Test HAVE_ATTRIBUTE_VISIBILITY_HIDDEN - Success
  -- Performing Test HAVE_ATTRIBUTE_VISIBILITY_INTERNAL
  -- Performing Test HAVE_ATTRIBUTE_VISIBILITY_INTERNAL - Success
  -- Performing Test HAVE_ATTRIBUTE_ALIGNED
  -- Performing Test HAVE_ATTRIBUTE_ALIGNED - Success
  -- Performing Test HAVE_THREAD_LOCAL
  -- Performing Test HAVE_THREAD_LOCAL - Success
  -- Performing Test HAVE_BUILTIN_CTZ
  -- Performing Test HAVE_BUILTIN_CTZ - Success
  -- Performing Test HAVE_BUILTIN_CTZLL
  -- Performing Test HAVE_BUILTIN_CTZLL - Success
  -- Performing Test HAVE_PTRDIFF_T
  -- Performing Test HAVE_PTRDIFF_T - Success
  -- Performing Test HAVE_AVX2_INTRIN
  -- Performing Test HAVE_AVX2_INTRIN - Success
  -- Performing Test HAVE_CASCADE_LAKE
  -- Performing Test HAVE_CASCADE_LAKE - Success
  -- Performing Test HAVE_AVX512_INTRIN
  -- Performing Test HAVE_AVX512_INTRIN - Success
  -- Performing Test HAVE_MASK_INTRIN
  -- Performing Test HAVE_MASK_INTRIN - Success
  -- Performing Test HAVE_AVX512VNNI_INTRIN
  -- Performing Test HAVE_AVX512VNNI_INTRIN - Failed
  -- Performing Test HAVE_SSE42CRC_INLINE_ASM
  -- Performing Test HAVE_SSE42CRC_INLINE_ASM - Success
  -- Performing Test HAVE_SSE42CRC_INTRIN
  -- Performing Test HAVE_SSE42CRC_INTRIN - Success
  -- Performing Test HAVE_SSE2_INTRIN
  -- Performing Test HAVE_SSE2_INTRIN - Success
  -- Performing Test HAVE_SSSE3_INTRIN
  -- Performing Test HAVE_SSSE3_INTRIN - Success
  -- Performing Test HAVE_PCLMULQDQ_INTRIN
  -- Performing Test HAVE_PCLMULQDQ_INTRIN - Success
  -- Performing Test HAVE_VPCLMULQDQ_INTRIN
  -- Performing Test HAVE_VPCLMULQDQ_INTRIN - Failed
  -- Performing Test HAVE_XSAVE_INTRIN
  -- Performing Test HAVE_XSAVE_INTRIN - Failed
  -- Architecture-specific source files: arch/x86/x86_features.c;arch/x86/slide_hash_avx2.c;arch/x86/chunkset_avx2.c;arch/x86/compare256_avx2.c;arch/x86/adler3
2_avx2.c;arch/x86/adler32_avx512.c;arch/x86/adler32_sse42.c;arch/x86/insert_string_sse42.c;arch/x86/chunkset_sse2.c;arch/x86/compare256_sse2.c;arch/x86/slide_h
ash_sse2.c;arch/x86/adler32_ssse3.c;arch/x86/chunkset_ssse3.c;arch/x86/crc32_pclmulqdq.c
  -- The following features have been enabled:

   * CMAKE_BUILD_TYPE, Build type: RelWithDebInfo (selected)
   * AVX2_SLIDEHASH, Support AVX2 optimized slide_hash, using "-mavx2"
   * AVX2_CHUNKSET, Support AVX2 optimized chunkset, using "-mavx2"
   * AVX2_COMPARE256, Support AVX2 optimized compare256, using "-mavx2"
   * AVX2_ADLER32, Support AVX2-accelerated adler32, using "-mavx2"
   * AVX512_ADLER32, Support AVX512-accelerated adler32, using "-mavx512f -mavx512dq -mavx512bw -mavx512vl -mtune=cascadelake"
   * SSE42_CRC, Support SSE4.2 optimized CRC hash generation, using "-msse4.2"
   * SSSE3_ADLER32, Support SSSE3-accelerated adler32, using "-mssse3"
   * PCLMUL_CRC, Support CRC hash generation using PCLMULQDQ, using "-mssse3 -msse4.2 -mpclmul"
   * WITH_GZFILEOP, Compile with support for gzFile related functions
   * ZLIB_COMPAT, Compile with zlib compatible API
   * ZLIBNG_ENABLE_TESTS, Test zlib-ng specific API
   * WITH_SANITIZER, Enable sanitizer support
   * WITH_GTEST, Build gtest_zlib
   * WITH_OPTIM, Build with optimisation
   * WITH_NEW_STRATEGIES, Use new strategies
   * WITH_AVX2, Build with AVX2
   * WITH_AVX512, Build with AVX512
   * WITH_SSE2, Build with SSE2
   * WITH_SSSE3, Build with SSSE3
   * WITH_SSE42, Build with SSE42
   * WITH_PCLMULQDQ, Build with PCLMULQDQ

  -- The following features have been disabled:

   * ZLIB_SYMBOL_PREFIX, Publicly exported symbols DO NOT have a custom prefix
   * ZLIB_ENABLE_TESTS, Build test binaries
   * WITH_FUZZERS, Build test/fuzz
   * WITH_BENCHMARKS, Build test/benchmarks
   * WITH_BENCHMARK_APPS, Build application benchmarks
   * WITH_NATIVE_INSTRUCTIONS, Instruct the compiler to use the full instruction set on this host (gcc/clang -march=native)
   * WITH_MAINTAINER_WARNINGS, Build with project maintainer warnings
   * WITH_CODE_COVERAGE, Enable code coverage reporting
   * WITH_INFLATE_STRICT, Build with strict inflate distance checking
   * WITH_INFLATE_ALLOW_INVALID_DIST, Build with zero fill for inflate invalid distances
   * WITH_AVX512VNNI, Build with AVX512 VNNI
   * WITH_VPCLMULQDQ, Build with VPCLMULQDQ
   * INSTALL_UTILS, Copy minigzip and minideflate during install

  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/cargo-install9cypfX/release/build/libz-sys-155c7672ee3f03e5/out/build
  running: cd "/tmp/cargo-install9cypfX/release/build/libz-sys-155c7672ee3f03e5/out/build" && MAKEFLAGS="-j --jobserver-fds=11,12 --jobserver-auth=11,12" "cmak
e" "--build" "." "--target" "install" "--config" "RelWithDebInfo"
  [  2%] Building C object CMakeFiles/zlib.dir/adler32.c.o

  --- stderr
  CMake Warning:
    Manually-specified variables were not used by the project:

      CMAKE_ASM_COMPILER
      CMAKE_ASM_FLAGS
      CMAKE_CXX_COMPILER
      CMAKE_CXX_FLAGS

  gmake[2]: *** read jobs pipe: Resource temporarily unavailable.  Stop.
  gmake[2]: *** Waiting for unfinished jobs....
  gmake[1]: *** [CMakeFiles/zlib.dir/all] Error 2
  gmake: *** [all] Error 2
  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 2

  build script failed, must exit now', /home/users/ywang285/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `fibertools-rs v0.3.6 (https://github.com/fiberseq/fibertools-rs#9839e249)`, intermediate artifacts can be found at `/tmp/cargo-instal
l9cypfX`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

**Comment by mrvollger** [comment]
I don't think I see the actual error here that is causing the build to fail, could you rerun with the backtrace flag set to get some more details? 

But in general, it might be hard for me to advise since I cannot reproduce this error. 

Maybe check closed issues in https://github.com/rust-lang/libz-sys/issues to see if someone had a similar issue that was resolved?

Sorry, I don't have better ideas.

**Comment by ywang285** [comment]
Thanks for your reply. So it turns out that our rust has some issues and after fixing that I successfully build fibertools-rs. By the way, does fibertools support multi GPU? In my test run I saw it only used cuda (0) even if I have more gpu.
