### ISSUE TITLE
pyft: Missing FIRE precision scores for MSPs in pyft.Ranges() class

### ISSUE THREAD

**Issue by aman62000** [fiberseq/fibertools-rs#41]
There is currently no way to access the precision scores when accessing fibers with pyft, requires the use of pysam 'aq' tag in order to get individual fiber FIRE precision value information. 

pyft version 0.1.12

**Comment by mrvollger** [comment]
I have added the ability in a branch called footprint, which you can install with:
```
pip install -e 'git+https://github.com/fiberseq/fibertools-rs.git@footprint#egg=pyft&subdirectory=py-ft'
```
but I don't have time to test so please try it out and share with me if it is working.

**Comment by mrvollger** [comment]
the data will be in 
```fiber.msp.qual```
