### ISSUE TITLE
ft center not working on K.marxianus data

### ISSUE THREAD

**Issue by shedou35** [fiberseq/fibertools-rs#48]
Hi Mitchell,
The ft center command gives an empty file when I use it on Fiber-seq data generated in the yeast K.marxianus. 
I tested the ft center command alone and it only gives the column names.

- The exact command
/mmfs1/gscratch/stergachislab/bin/ft center -m 200 -d 1000 -w -r -t 40 PS00527.phased.bam Kmarxianus_CEN_center.bed | cutnm chrom,reference_start,reference_end,strand | awk 'NR > 1' | sort-bed - > PS00527_output2.bed 

- file path
/gscratch/stergachislab/shedou/projects/yeast1/

OS: [Linux]

Thank you very much for your help!

- Sabrine

**Comment by mrvollger** [comment]
Your bam files have no reads that overlap these regions. This can be tested like:
```
# count (-c) n reads overlapping the bed records
$ samtools view -c -M -L Kmarxianus_CEN_center.bed PS00527.phased.bam
# results
0
```
I would check your bed file to make sure it is correct, make sure the bam file is aligned to the right genome, and finally, do a coverage analysis of the bam to see if you are getting the data you expected. 

Good luck, 
Mitchell
