### ISSUE TITLE
"Illegal instruction" after updating to latest version of fibertools-rs

### ISSUE THREAD

**Issue by ywang285** [fiberseq/fibertools-rs#49]
Hi Mitchell, I recently updated fibertools-rs to the latest version and when I type ft command, it gives "Illegal instruction". The version that I installed in Nov 2023 (I believe it was 0.3.6) works fine. Although I can still use the old version to add-nucleosomes, etc, it seems that FIRE workflow automatically install the latest version of fibertools-rs and give "Illegal instruction" error message. I searched on github and it seems that this error message is associated with old cpu. But my cpu is AMD 5995WX which I think should not be that "old". Do you have any idea about this issue? Thank you!

**Comment by mrvollger** [comment]
I am not able to recreate this issue on any of my machines or with any of the install methods. Maybe just trying un and reinstalling?

**Comment by geocarvalho** [comment]
Hi, just had the same issue with `0.4.2-0` from conda, when I get back to `0.4.1-0` it works fine.
I'm using an EC2 AWS machine:

```bash
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by ddubocan** [comment]
Hi Mitchell, 

I also experienced the same issue with 0.4.2 from conda, reverting to 0.4.1 seemed to fix the issue. 
Using a CentOS 7 machine.

**Comment by mrvollger** [comment]
I am still unable to replicate this locally with GCC versions 9-13, and the conda recipe is unchanged between 4.1 and 4.2, so I don't know where to start here, unfortunately.
https://github.com/bioconda/bioconda-recipes/pull/46660/files

**Comment by mrvollger** [comment]
I made a change to the build rules as a potential fix in bioconda that should appear online as version 0.4.2-1 in the next hour or so. Please let me know if it fixes this for you.

**Comment by mrvollger** [comment]
Fixed with bioconda patch update. Reopen if you find otherwise.
