### ISSUE TITLE
add-nucleosomes --min-ml-score option set to small values results in no nuc, msp or fire calls

### ISSUE THREAD

**Issue by MariosEft97** [fiberseq/fibertools-rs#52]
Hello! Thank you for developing such an amazing tool!

When using the `ft add-nucleosomes` command with the `--min-ml-score` option set to a small value, I noticed that the `ns`, `nl`, `as`, `al` and `aq` tags’ information are missing from the resulting bed file of `ft extract` command (they appear as ‘.’ in the corresponding entries).

Environment:
- **OS**: Rocky Linux release 8.9 (Green Obsidian)
- **fibertools-rs**: 0.4.2

Commands used:
```python
!samtools view -b -h --threads $cores $pacbio_bam chr1:226672641-226673664 > view.bam
``` 
```python
!ft add-nucleosomes --min-ml-score 0 --threads $cores view.bam nuc_msp.bam
``` 
```python
!ft fire --threads $cores nuc_msp.bam nuc_msp_fire.bam
``` 
```python
!ft extract --simplify --threads $cores nuc_msp_fire.bam --all ft_tag.bed.gz
```
```python
tag_bed_df = pd.read_csv(
    "ft_tag.bed.gz",
    sep='\t',
    usecols=['#ct', 'st', 'en', 'fiber', 'nuc_starts', 'nuc_lengths', 'ref_nuc_starts', 'ref_nuc_lengths', 'msp_starts', 'msp_lengths', 'ref_msp_starts', 'ref_msp_lengths', 'fire']
)

tag_bed_df.head()

```

Screenshot:
<img width="1682" alt="Screenshot 2024-05-28 at 15 08 32" src="https://github.com/fiberseq/fibertools-rs/assets/75463314/3d621a3b-81af-468e-b52d-21eaf8424c5c">

In this example I set the `--min-ml-score 0`, but I have tried other values as well. I could reproduce the same results with values <= 67. Is there a minimum eligible score for `--min-ml-score` option?

`view.bam` can be downloaded with:
```shell
wget -O view.bam "https://drive.google.com/uc?export=download&id=1h3Zn_neSSnKGJKsZXTLVig8JrgpAFOJs"
```

**Comment by mrvollger** [comment]
This does appear to be a bug when using the `--min-ml-score` option (otherwise, it seems to be working).

I am investigating.

**Comment by mrvollger** [comment]
Never mind, this is not a bug. The bam file you shared contains low ML value calls for essentially every A/T bp in the reads. To see this, you can do:
```
ft add-nucleosomes  view.bam | ft extract --min-ml-score 0 --all - | hck -F m6a_qual |  sed 's/,/\n/g' | sort -n | uniq -c
```
and see:
```
...
2195 0
4314 1
4291 2
4382 3
4325 4
4086 5
3947 6
3752 7
....
1587 250
1998 251
2844 252
4143 253
7807 254
42135 255
```
If every base is marked with an m6A (even with a low ML score), the tool will (correctly) find no nucleosome footprints. 

If this is ONT data I recommend using 250 as a cutoff. If this is pacbio data then we recommend you do not manually select the m6A threshold unless you have a very explicit reason to do so when using `predict-m6a`. We invested a fair amount of time selecting the defaults for each pacbio chemistry to pull out the best fiber-seq results.
