### ISSUE TITLE
how to state the genome 6mA marks 

### ISSUE THREAD

**Issue by cell-c** [fiberseq/fibertools-rs#58]
Thanks for providing fibertools-rs. It is an excellent tool for detecting 6mA marks using PacBio HiFi sequencing.

I don't find this function in fibertools-rs about the statistics of the genome 6mA marks. How is this function of the software found? Thanks.

**Comment by mrvollger** [comment]
If you share a little about your application and I can be more specific but generally I recommend fibertools because ipdSummary has never been explicitly updated for HiFi data.

**Comment by mrvollger** [comment]
Can you elaborate on what you are looking for?

**Comment by mrvollger** [comment]
We have added a command called ft qc that should resolve this.

**Comment by cell-c** [comment]
Hi, I am sorry for missing your response. Accturaly,  I predicted the 6mA and 5mc marks using this tool. I want to obtain the methylation statistics in the reference genome. Currently I map the methylation bam result to the reference genome using pbmm2 and analyse the methylation information in the reference genome using the coverage of methylation sites. Do you have any suggestions about the statistics ? Thank you.

**Comment by StephanieBohaczuk** [comment]
Maybe you're looking for this? https://github.com/fiberseq/FIRE
