### ISSUE TITLE
MissingInputException error when running fiberseq-smk

### ISSUE THREAD

**Issue by AnnaE-F** [fiberseq/fibertools-rs#62]
Hello,
I am trying to run snakemake (on linux, on a cluster) and I am facing a "MissingInputException" error. I have seen several similar issues reported on the internet but I don't know how to fix mine. 

This is what I typed:

sbatch [options]  \
      snakemake --profile profile/compute \
                --config env="fiberseq-smk" \
                anna_sub_1=[path to my bam file] \
                ref=[path to my reference]

and here is the error message:

MissingInputException in rule split_ccs in file /pasteur/appa/homes/aesposit/fiberseq-smk/workflow/rules/ccs.smk, line 85:
Missing input files for rule split_ccs:
    output: temp/anna_sub_1/split_ccs/ccs.1-of-1.bam, temp/anna_sub_1/split_ccs/ccs.1-of-1.bam.pbi
    wildcards: sm=anna_sub_1, scatteritem=1-of-1
   affected files:
        [path to bam file].pbi

I have pasted in the following text file the content of the ccs.smk, which seems to be the problem:
[ccssmk.odt](https://github.com/user-attachments/files/17165265/ccssmk.odt)

Thank you, and have a nice day!

**Comment by mrvollger** [comment]
We are no longer maintaining or supporting fiberseq-smk since this tool is now replaced by ft. You can read the readme of this repository and follow our quick start guide to learn about using ft https://fiberseq.github.io/quick-start.html
