### ISSUE TITLE
False methylations called in first 7 or so bp

### ISSUE THREAD

**Issue by mtcicero26** [fiberseq/fibertools-rs#65]
- Fibertools reports all A/T bp in the first and last 8 bp of the read as methylated (which should instead be masked due to the window used by the caller). This may be a Revio-specific issue. 
- This occurs for any usage of m6a-calling with several recent versions of fibertools (0.3.1, 0.4.2)

**Example output (bed)**
fiber_sequence     AAACAAATGCTGAGGCCATTCTCCTGTTCTGCTTCCTGGCACTACG...
m6a                0,1,2,4,5,6,21,318,1170,2616,2884,4133,4567,47...
ref_m6a            -1,-1,-1,-1,-1,-1,-1,33455045,33455907,3345735..

**Example command**
ft predict-m6a -t 8 -k IN.bam OUT.bam

**Comment by mtcicero26** [comment]
Also, it should be noted that the -1s in the example ref_m6a output do not consistently show up-- if that part of the read aligned, they will show correct reference coordinates for the false methylations.

**Comment by mrvollger** [comment]
This will be fixed in the next release and can be tested in this PR #64. This issue seems to be limited to the first and last 7bp in Revio data, and would not have impacted MSP or NUC calling in fibertools since we don't start calling until the 45th bp.

**Comment by mtcicero26** [comment]
As a note, I've already accounted for this with FiberHMM, so it should have no effect on footprint calling either.

**Comment by mrvollger** [comment]
Great news! I am reopening until I merge the fix.
